name: Paul Chiusano's blog
url: http://pchiusano.github.io

permalink: /:month-:day-:year/:title.html
pygments: true
markdown: kramdown
kramdown:
  input: GFM
  fenced_code_blocks: true
  
paginate: 5
