name: Paul Chiusano's blog
url: http://pchiusano.github.io

permalink: /:year-:month-:day/:title.html
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  fenced_code_blocks: true
  
paginate: 5
