name: Paul Chiusano's blog
url: http://pchiusano.github.io

permalink: /:year-:month-:day/:title.html
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  fenced_code_blocks: true
  
paginate: 5
