name: Paul Chiusano's blog
url: http://pchiusano.github.io

permalink: /:year-:month-:day/:title.html
pygments: true
markdown: kramdown
kramdown:
  input: GFM
  fenced_code_blocks: true
  
paginate: 5
